### ISSUE TITLE
Adding new cards will not update the tags.

### ISSUE THREAD

**Issue by praveenscience** [CloudroitHQ/Light-Weight-Kanban#1]

**Comment by superpower1** [comment]
I can help with this one

**Comment by praveenscience** [comment]
Thanks @superpower1!

**Comment by praveenscience** [comment]
There's a small problem with this approach. It also gets the `Unassigned` tag, if we remove it. Looks like it's getting cached somewhere?

**Comment by superpower1** [comment]
It will scan and store all the tags once a card is submitted. so if a new card is submitted as default unassigned then `Unassigned` will be a tag as well. I can make another PR to ignore Unassigned if that is the case.

Also, sorry that I forgot to apply my function to delete process. The tag list will not update when you delete a card at the moment. I will make a PR to solve this problem.

**Comment by praveenscience** [comment]
Go for it... And thanks mate... 😃

**Comment by praveenscience** [comment]
@superpower1 Can this be closed now?

**Comment by superpower1** [comment]
> @superpower1 Can this be closed now?

Yes, this one is solved.

**Comment by vamshisuram** [comment]
@praveenscience can you please the close the issue?

**Comment by praveenscience** [comment]
@vamshisuram Sure... :+1:
