### ISSUE TITLE
Cannot use mouse to select text when editing

### ISSUE THREAD

**Issue by superpower1** [CloudroitHQ/Light-Weight-Kanban#10]
Mouse up event will trigger submit

**Comment by praveenscience** [comment]
Hi @superpower1, accepted your PR. Does that fix it or is this new one?

**Comment by superpower1** [comment]
It's a new one, found it when I am playing with the app. 😃  I can also look into this.

**Comment by praveenscience** [comment]
@superpower1 Go for it... Thanks! 😃
