### ISSUE TITLE
No .gitignore file in project

### ISSUE THREAD

**Issue by wadleo** [CloudroitHQ/Light-Weight-Kanban#14]
I think we need a .gitignore file because some files like the data file, should not be shared and should be local to each developer's instance. Also, the readme should be updated to recommend the user to create his own data file which will not be shared. @praveenscience @cloudroit please let me know what you think, so I can make the changes, thanks.

**Comment by praveenscience** [comment]
@wadleo I don't think that's needed. I believe there's already one. So you mean to say after a first run? In that case, yea, go ahead and create one. 👍

**Comment by wadleo** [comment]
I think we can close this now @praveenscience

**Comment by praveenscience** [comment]
Yea, it's closed by you already... 👍
