### ISSUE TITLE
Limit tag size.

### ISSUE THREAD

**Issue by praveenscience** [CloudroitHQ/Light-Weight-Kanban#6]

**Comment by wadleo** [comment]
Please can you give more details, do you mean in the string length when displaying it at the bottom?

**Comment by praveenscience** [comment]
Check this out:

![image](https://user-images.githubusercontent.com/1830380/47785624-2a594780-dd01-11e8-9fa1-9d9ba382a743.png)

That needs to be limited. LoL. 😄  @wadleo

**Comment by wadleo** [comment]
@praveenscience thanks, I was just testing that out while waiting for your feedback.

**Comment by wadleo** [comment]
Okay, I'm on it.

**Comment by wadleo** [comment]
@praveenscience I will display 10 characters and the full one will be shown when a client hovers over the tag (using the title attribute on the label for that input). Also, I have added some ellipses to indicate that tag has been shortened.

**Comment by praveenscience** [comment]
Thanks @wadleo! 👍
